# Generated by Django 4.0.5 on 2022-07-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('solicitante', models.CharField(max_length=20)),
                ('inicio_vacaciones', models.DateField()),
                ('fin_vacaciones', models.DateField()),
            ],
        ),
    ]
